version: '3.6'

services:
  rentalapi:
    build: ./rentalapi
    depends_on:
      - rentalpgdb
      - rentalredis
    links:
      - rentalpgdb
    ports:
      - '8098:8000'
    volumes:
      - ./rentalapi:/rentalapi
    env_file: conf/dev.env
    command: ['flask', 'run', '--host=0.0.0.0', '--port=8000']

  rentalpgdb:
    image: postgres:alpine
    env_file: conf/dev.env
    # ports:
    #   - '5433:5432'
    volumes:
      - rentaldb_volume:/var/lib/postgresql

  rentalredis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - rentalredis_volume:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf

  rentalapp:
    build: ./rentalapp
    depends_on:
      - rentalapi
    ports:
      - '8097:8080'
    volumes:
      - ./rentalapp:/rentalapp
    command: ['yarn', 'serve']

volumes:
  rentaldb_volume:
  rentalredis_volume: