version: '3.6'

services:
  api:
    build: 
      context: ./rentalapi
      target: development
    depends_on:
      - db
      - cache
    links:
      - db
    ports:
      - '8098:8000'
    volumes:
      - ./rentalapi:/rentalapi
    env_file: conf/dev.env
    command: [ 'sh', '/tmp/wait-for.sh', 'db:5432', '-t', '30', '--', 'flask', 'run', '--host=0.0.0.0', '--port=8000']

  db:
    image: postgres:alpine
    container_name: rentaldb
    env_file: conf/dev.env
    volumes:
      - db_volume:/var/lib/postgresql

  cache:
    image: redis:alpine
    container_name: rentalredis
    volumes:
      - cache_volume:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf

  frontend:
    build: ./rentalapp
    depends_on:
      - api
    ports:
      - '8097:8080'
    volumes:
      - ./rentalapp:/rentalapp
    command: ['yarn', 'serve']

  pgadmin:
    image: dpage/pgadmin4:5.4
    env_file: conf/dev.env
    links:
      - db
    ports:
      - '8100:80'

volumes:
  db_volume:
  cache_volume: