version: '3.6'

services:
  rentalapi:
    build: ./rentalapi
    restart: always
    depends_on:
      - rentalpgdb
      - rentalredis
    env_file: conf/prod.env
    command: sh /tmp/wait-for.sh rentalpgdb:5432 -t 30 -- gunicorn --reload --log-level debug --preload -w 4 -b 0.0.0.0:8000 rentalapi.app:create_app()

  rentalpgdb:
    env_file: conf/prod.env
    restart: always
    image: postgres:alpine
    volumes:
      - prod_db_volume:/var/lib/postgresql

  rentalapp:
    build: 
      context: ./rentalapp
      target: production
    restart: always
    ports:
      - '80:80'
    links:
      - rentalapi
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  rentalredis:
    image: redis:alpine
    restart: always
    volumes:
      - prod_cache_volume:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  prod_db_volume:
  prod_cache_volume:
