"""empty message

Revision ID: 13170309d8bc
Revises: 
Create Date: 2021-07-07 13:13:30.455691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13170309d8bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('user_age', sa.Integer(), nullable=False))
    op.add_column('rentals', sa.Column('pickup', sa.String(length=150), nullable=False))
    op.add_column('rentals', sa.Column('dropoff', sa.String(length=150), nullable=True))
    op.add_column('rentals', sa.Column('pickup_date', sa.DateTime(), nullable=False))
    op.add_column('rentals', sa.Column('dropoff_date', sa.DateTime(), nullable=False))
    op.add_column('rentals', sa.Column('dispatch_date', sa.DateTime(), nullable=True))
    op.add_column('rentals', sa.Column('return_date', sa.DateTime(), nullable=True))
    op.drop_column('rentals', 'returned')
    op.drop_column('rentals', 'dispatched')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('dispatched', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('rentals', sa.Column('returned', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('rentals', 'return_date')
    op.drop_column('rentals', 'dispatch_date')
    op.drop_column('rentals', 'dropoff_date')
    op.drop_column('rentals', 'pickup_date')
    op.drop_column('rentals', 'dropoff')
    op.drop_column('rentals', 'pickup')
    op.drop_column('rentals', 'user_age')
    # ### end Alembic commands ###
