"""empty message

Revision ID: b8ddb0d0eb3a
Revises: daba206749f8
Create Date: 2021-07-07 13:53:43.868718

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8ddb0d0eb3a'
down_revision = 'daba206749f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('discount', sa.Float(), nullable=True))
    op.drop_column('rentals', 'discont')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('discont', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('rentals', 'discount')
    # ### end Alembic commands ###
