import os

DATABASE_URI = os.environ['SQLALCHEMY_DATABASE_URI']

CELERY_RESULT_BACKEND = os.environ['CELERY_RESULT_BACKEND']
CELERY_BROKER_URL = os.environ['CELERY_BROKER_URL']

JWT_SECRET_KEY = os.environ['JWT_SECRET_KEY']